data:
  dataset_yaml: '/userhome/wangbingxuan/code/MeshGraphormer/src/datasets/dataset.yaml'
  dataset: ['interhand', 'evrealhands']
  event: True # unused
  smplx_path: '/userhome/alanjjp/data/smplx_models/mano'
  rgb_hw: [920, 1064] # unused
  event_hw: [260, 346] # unused

model:
  bert_config: 'src/modeling/bert/bert-base-uncased/'
  method:
    framework: "pretrain" #'perceiver' #'encoder_decoder_based' # 'encoder_decoder_based' # "pretrain"
    ere_usage: [False, True, False]
  tfm:
    # config for FASTMETRO
    scale: 'L' # 'S', 'M', 'L'
    model_dim: [512, 128]
    feedforward_dim: [1024, 256]
    pos_type: 'sine'
    nhead: 8
    n_self_att_layers: 2
    iterations: 1
    perceiver_layers: 2
    decoder_features: [False, True, False]
    output_attentions: True
    drop_out: 0.1
    mesh_type: 'hand'
    num_hidden_layers: 4
    num_attention_heads: 4
    hidden_size: -1
    intermediate_size: -1
    input_feat_dim: [ 2051, 512, 128 ]
    hidden_feat_dim: [ 1024,256,64 ]
    which_gcn: [ 0, 0, 1 ]
  backbone:
    arch: 'hrnet'
    hrnet_yaml: 'models/hrnet/cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml'
    hrnet_bb: 'models/hrnet/hrnetv2_w64_imagenet_pretrained.pth'


exper:
  debug: False
  run_eval_only: False
  resume_checkpoint: '/userhome/wangbingxuan/code/MeshGraphormer/output/debug_pretrain_2/checkpoint-10-8180/state_dict.bin'
  num_workers: 8
  output_dir: './output'
  per_gpu_batch_size: 32
  lr: 0.0001
  num_train_epochs: 200
  device: 'cuda'
  seed: 88
  distributed: True #True
  # ground truth if true else weakly
  supervision: False # should be false
  use_gt: True # should be false
  fine_tune_weakly: True # True to pretrain, False for inference
  seg_kpt_model_path: "/userhome/wangbingxuan/code/MeshGraphormer/models/self_super/SegAndKptModel.pth"
  preprocess:
    ere_rate: 1.0 # unused
    left_window: [3000, 1000000]
    ev_repre: 'LNES' #'Lnes', 'eci'
    event_range: 'num' # 'time'
    num_window: 7000
    num_var: 2000
    cam_view: 'rgb' # 'world', 'rgb', 'event
    steps: 1
    segments: 1
  augment:
    geometry:
      scale: 0.1
      trans: 0.05
      rot: 0.2
    rgb_photometry:
      colorjitter:
        p: 0.15
        brightness:
          thre: [0.6, 5.]
      gauss:
        var: [0.1, 0.2]
        p: 0.5
      gaussianblur:
        p: 0.1
        kernel_size: 19
        sigma: [4, 8]
      salt_pepper:
        p: 0.0
        rate: 0.1
    event_photometry:
      colorjitter:
        p: 0.0
        brightness:
          thre: [0.6, 5.]
      gauss:
        var: [0.05, 0.1]
        p: 0.2
      gaussianblur:
        p: 0.0
        kernel_size: 31
        sigma: [0.1, 0.3]
      salt_pepper:
        p: 0.1
        rate: 0.1
  bbox:
    rate: 1.5
    rgb:
      size: 192
    event:
      size: 128
  loss:
    vertices: 100.0
    vertices_sub: 100.0
    3d_joints: 2000.0
    3d_joints_from_mesh: 1000.0
    seg_rgb: 10.0
    seg_event: 10.0
    2d_joints_rgb: 50.
    2d_joints_event: 50.
    bce_rgb: 0.001
    bce_event: 0.001

eval:
  fast: False
  multiscale_inference: False
  augment:
    rot: 0
    scale: 1.0
  fast_fps: 120
  fast_window: 5000
  output:
    save: False
    mesh: True
    attention_map: True
    errors: True
    rendered: True
    vis_rendered: 'event'

utils:
  logging_steps: 10