data:
  dataset_yaml: '/userhome/alanjjp/Project/MeshGraphormer/src/datasets/dataset.yaml'
  dataset: ['evrealhands']
  smplx_path: '/userhome/alanjjp/data/smplx_models/mano'
exper:
  debug: True
  num_workers: 4
  per_gpu_batch_size: 16
  preprocess:
    ev_repre: 'LNES' #'Lnes', 'eci'
    event_range: 'num' # 'time'
    num_window: 7000

eval:
  fast_fps: 30 #120
  fast_window: 5000
  multiscale: False
  output:
    save: True
    mesh: True
    attention_map: True
    errors: True
    rendered: True
    vis_rendered: 'event'
  augment:
    scale: 1.0
    rot: 0.0
utils:
  logging_steps: 10