data:
  dataset_yaml: '/userhome/alanjjp/Project/MeshGraphormer/src/datasets/dataset.yaml'
  dataset: ['evrealhands']
exper:
  debug: False
  num_workers: 6
  per_gpu_batch_size: 64
  preprocess:
    ere_rate: 1.0
    left_window: [3000, 1000000]
    ev_repre: 'LNES' #'Lnes', 'eci'
    event_range: 'num' # 'time'
    num_window: 5000

eval:
  fast_fps: 15
  fast_window: 5000
  multiscale: False
  output:
    save: False
    mesh: True
    attention_map: True
    errors: True
    rendered: True
    vis_rendered: 'rgb'
  augment:
    scale: 1.0
    rot: 0.0
utils:
  logging_steps: 10