sub_ids: [0, 2, 4, 5, 6, 7, 8, 9]
seq_ids_path: 'id_seq_right.json'
name_map_path: 'name_map.json'
trace_map_path: 'trace_map.json'
camera_pairs: [['event', '21320028']]
#, ['event', '21320029'], ['event', '21320030'], ['event', '21320034'], ['event', '21320035'], ['event', '21320036']]